version: '3.8'

services:
  mysql:
    image: mysql:8.0
    volumes:
      - mysql-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: escolaingles
    ports:
      - 3306:3306

volumes:
  mysql-db: